--- unit_tests/test_twisted.py.orig	2007-04-22 01:40:41.000000000 +0300
+++ unit_tests/test_twisted.py	2007-09-14 12:42:32.000000000 +0300
@@ -7,28 +7,6 @@
 class CustomError(Exception):
     pass
 
-# Should succeed unless python-hosting is down
-#@deferred
-def test_resolve():
-    return reactor.resolve("nose.python-hosting.com")
-test_resolve = deferred()(test_resolve)
-
-# Raises TypeError because the function does not return a Deferred
-#@raises(TypeError)
-#@deferred()
-def test_raises_bad_return():
-    reactor.resolve("nose.python-hosting.com")
-test_raises_bad_return = raises(TypeError)(deferred()(test_raises_bad_return))
-
-# Check we propagate twisted Failures as Exceptions
-# (XXX this test might take some time: find something better?)
-#@raises(DNSLookupError)
-#@deferred()
-def test_raises_twisted_error():
-    return reactor.resolve("x.y.z")
-test_raises_twisted_error = raises(DNSLookupError)(
-    deferred()(test_raises_twisted_error))
-
 # Check we detect Exceptions inside the callback chain
 #@raises(CustomError)
 #@deferred(timeout=1.0)
