# ChangeLog for dev-python/python-selinux
# Copyright 2000-2003 Gentoo Technologies, Inc.; Distributed under the GPL v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/python-selinux/ChangeLog,v 1.4 2003/07/30 01:20:51 method Exp $

*python-selinux-1.2 (29 Jul 2003)

  29 Jul 2003; Joshua Brindle <method@gentoo.org> python-selinux-1.2.ebuild:
  new version that throws correct exception

*python-selinux-1.1 (29 Jul 2003)

  29 Jul 2003; Joshua Brindle <method@gentoo.org> python-selinux-1.1.ebuild:
  fixed it so that it will throw an exception on load if no selinux kernel

*python-selinux-1.0-r1 (09 Jul 2003)

  09 Jul 2003; Joshua Brindle <method@gentoo.org>
  python-selinux-1.0-r1.ebuild: 
  wow, what was i thinking with that ebuild, this one should really work

*python-selinux-1.0 (03 Jul 2003)

  03 Jul 2003; Joshua Brindle <method@gentoo.org> python-selinux-1.0.ebuild:
  Initial commit, thanks to torbenh for writing this for us :)

