Index: test_vc.py
===================================================================
RCS file: /cvsroot/buildbot/buildbot/buildbot/test/test_vc.py,v
retrieving revision 1.68
retrieving revision 1.69
diff -u -d -r1.68 -r1.69
--- buildbot/test/test_vc.py	15 Sep 2006 14:47:41 -0000	1.68
+++ buildbot/test/test_vc.py	18 Sep 2006 02:14:45 -0000	1.69
@@ -499,6 +499,15 @@
             self.fail("build did not succeed")
         return bs
 
+    def printLogs(self, bs):
+        for s in bs.getSteps():
+            for l in s.getLogs():
+                print "--- START step %s / log %s ---" % (s.getName(),
+                                                          l.getName())
+                print l.getTextWithHeaders()
+                print "--- STOP ---"
+                print
+
     def touch(self, d, f):
         open(os.path.join(d,f),"w").close()
     def shouldExist(self, *args):
@@ -666,7 +675,12 @@
         d.addCallback(self._do_vctest_update_retry_1)
         return d
     def _do_vctest_update_retry_1(self, bs):
-        self.shouldNotExist(self.workdir, "newfile")
+        # SVN-1.4.0 doesn't seem to have any problem with the
+        # file-turned-directory issue (although older versions did). So don't
+        # actually check that the tree was clobbered.. as long as the update
+        # succeeded (checked by doBuild), that should be good enough.
+        #self.shouldNotExist(self.workdir, "newfile")
+        pass
 
     def _do_vctest_copy(self, res):
         d = self.doBuild() # copy rebuild clobbers new files
